server:
  port: 8080

spring:
  liquibase:
    changelog: ${LIQUIBASE_CHANGE_LOG:classpath:db/changelog/changelog-dev.xml}

  datasource:
    url: jdbc:h2:file:./db
    username: u
    password:

  jpa:
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: true
        show_sql: true
        format_sql: false
        ddl-auto: none

  h2:
    console:
      enabled: false

